services:
  http_server:
    build:
      dockerfile: http_server/Dockerfile
    ports:
      - 8080:8080
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=5672
    depends_on:
      consumer:
        condition: service_started
    healthcheck:
      test: curl --fail -X GET http://http_server:8080/health || exit 1
      interval: 3s
      timeout: 3s
      retries: 1

  broker:
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3

  consumer:
    build:
      dockerfile: consumers/code_processor/Dockerfile
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=5672
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      broker:
        condition: service_healthy

  tester:
    build:
      dockerfile: tests/Dockerfile
    environment:
      - HTTP_HOST=http_server
      - HTTP_PORT=8080
    profiles:
      - test
    depends_on:
      http_server:
        condition: service_healthy
